### ISSUE TITLE
Python 3 listcomp not updating

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#238]
I'm trying to filter a table, however this simple example is not working in python3 (on the current master branch).

```python

from enaml.widgets.api import Window, Container, Label, Field


enamldef Main(Window):
    Container:
        attr colors = ['red', 'blue', 'yellow', 'green']
        Field: search:
            placeholder = "Search..."
        Label:
            text << '{}'.format(search.text)
        Label:
            text << '{}'.format([c for c in colors
                                    if not search.text or search.text in c])

```

The second Label displays correctly initially but never updates thereafter. The first Label works as expected. Both work fine in Python 2.7.  

I tried a few more and it seems to be only with generator expressions on the RHS, so pulling the filtering out into a function is a workaround (and maybe a better to do it anyways). 

```python

from enaml.widgets.api import Window, Container, Label, Field

STATIC_COLORS = ['red', 'blue', 'yellow', 'green']

def echo(text):
    return text

def echo_gen(text):
    return [text for i in range(3)]

def echo_global(text):
    return [c for c in STATIC_COLORS if text in c]

def echo_ref(text, colors):
    return [c for c in colors if text in c]

enamldef Main(Window):
    Container: container:
        attr colors = ['red', 'blue', 'yellow', 'green']
        Field: search:
            placeholder = "Search..."

        Label: t1:
            #: Works
            text << '{}'.format(search.text)

        Label: t2:
            #: Works
            text << '{}'.format([search.text])

        Label: t3:
            #: Works
            text << '{}'.format(echo(search.text))
        Label: t4:
            #: Works
            text << '{}'.format(echo_gen(search.text))
        Label: t5:
            #: Works
            text << '{}'.format(echo_global(search.text))
        Label: t6:
            #: Works
            text << '{}'.format(echo_ref(search.text, colors))
        Label: t7:
            #: Doesn't update in 2.7 (master) OR 3.5
            text << '{}'.format({i:search.text for i in range(3)})
        Label: t8:
            #: Doesn't update in 3.5
            text << '{}'.format([search.text for i in range(3)])
        Label: t9:
            #: Doesn't update in 3.5
            text << '{}'.format([c for c in colors
                                    if not search.text or search.text in c])

```

The dict one is not working in 2.7 or python 3 (master branch). Interestingly, if I use enaml==0.9.8 it won't run unless that's commented out (gives a `NameError: global name 'search' is not defined`) so I assume dict comps never were supported.

**Comment by MatthieuDartiailh** [comment]
Thanks for reporting I will try to look into it. Dict comprehensions were not supported under 0.9.8 you are right. When you mean does not work for the dict, should I understand does not update or is it something else ?

**Comment by MatthieuDartiailh** [comment]
Good news I do have a fix. I will open a PR shortly for review and work on adding more tests in the meantime.

**Comment by frmdstryr** [comment]
I just pulled https://github.com/nucleic/enaml/pull/239 and tested it out. The example I showed works fine but now I'm getting a crash due to a NameError (passing a lambda to sorted)

```
Traceback (most recent call last):
  File "./venv/lib/python3.5/site-packages/enaml/qt/q_deferred_caller.py", line 42, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "./app/manifest.enaml", line 58, in start_default_workspace
    ui.select_workspace('app.editor')
  File "./venv/lib/python3.5/site-packages/enaml/workbench/ui/ui_plugin.py", line 158, in select_workspace
    self._model.workspace = new_workspace
  File "./venv/lib/python3.5/site-packages/enaml/core/standard_tracer.py", line 61, in __call__
    engine.update(owner, self.name)
  File "./venv/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 248, in update
    setattr(owner, name, pair.reader(owner, name))
  File "./venv/lib/python3.5/site-packages/enaml/core/include.py", line 85, in _observe_objects
    self.parent.insert_children(self, newvalue)
  File "./venv/lib/python3.5/site-packages/enaml/core/object.py", line 228, in insert_children
    child_added(child)
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 182, in child_added
    super(ToolkitObject, self).child_added(child)
  File "./venv/lib/python3.5/site-packages/enaml/styling.py", line 343, in child_added
    super(Stylable, self).child_added(child)
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 142, in child_added
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 119, in initialize
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 119, in initialize
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 119, in initialize
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 119, in initialize
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative.py", line 119, in initialize
    child.initialize()
  File "./venv/lib/python3.5/site-packages/enaml/core/pattern.py", line 38, in initialize
    self.refresh_items()
  File "./venv/lib/python3.5/site-packages/enaml/core/looper.py", line 96, in refresh_items
    iterable = self.iterable
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative_meta.py", line 43, in __call__
    value = engine.read(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 186, in read
    return pair.reader(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/standard_handlers.py", line 101, in __call__
    return call_func(func, (tr,), {}, scope)
  File "./app/workspaces/editor/views/modules.enaml", line 28, in <module>
    iterable << tree.items
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative_meta.py", line 43, in __call__
    value = engine.read(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 186, in read
    return pair.reader(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/standard_handlers.py", line 101, in __call__
    return call_func(func, (tr,), {}, scope)
  File "./app/workspaces/editor/views/modules.enaml", line 26, in <module>
    items << [m for m in modules if not search.text or search.text in m[0]]
  File "./venv/lib/python3.5/site-packages/enaml/core/declarative_meta.py", line 43, in __call__
    value = engine.read(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 186, in read
    return pair.reader(owner, name)
  File "./venv/lib/python3.5/site-packages/enaml/core/standard_handlers.py", line 101, in __call__
    return call_func(func, (tr,), {}, scope)
  File "./app/workspaces/editor/views/modules.enaml", line 17, in <module>
    attr modules << sorted(plugin.modules.items(),
  File "./workspaces/editor/views/modules.enaml", line 18, in <lambda>
    key=lambda m: m[0])
NameError: name '_[tracer]' is not defined
Fatal Python error: Aborted
```

**Comment by frmdstryr** [comment]
This is the relevant code

```
enamldef ModuleView(Container): view:
    attr plugin
    attr modules << sorted(plugin.modules.items(),
                           key=lambda m: m[0])
    Field: search:
        placeholder = "Search..."
        submit_triggers = ['auto_sync']
    TreeView: tree:
        horizontal_headers << ['Module', 'Attr', 'Type', 'Value']
        horizontal_stretch = True
        items << [m for m in modules if not search.text or search.text in m[0]]
```

**Comment by frmdstryr** [comment]
I can seem to reproduce this error in a simple example, will open another ticket if needed.

**Comment by frmdstryr** [comment]
@MatthieuDartiailh / @sccolbert  Please let me know if I should make a new issue. The local scope seems to be missing in 3.x due to this change. See below:

```
from enaml.widgets.api import Window, Container, PushButton


enamldef Main(Window):
    Container:
        PushButton:
            text = "Test local"
            #: Does not work in 3.5 but works in 2.7
            clicked ::
                j = 1
                matches = [i for i in range(10) if i==j]
                print("Pass")
        PushButton:
            text = "Test scope"
            attr j = 1
            #: Works fine
            clicked ::
                matches = [i for i in range(10) if i==j]
                print("Pass")
```


```
Traceback (most recent call last):
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/qt_abstract_button.py", line 77, in on_clicked
    self.declaration.clicked(checked)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "tests/example.enaml", line 14, in <module>
    matches = [i for i in range(10) if i==j]
  File "tests/example.enaml", line 14, in <listcomp>
    matches = [i for i in range(10) if i==j]
NameError: name 'j' is not defined
```

I'm getting some weird cases where it's saying that some imports don't exist when updating a doc area layout and boiled it down to this.

**Comment by frmdstryr** [comment]
It seems to depend on the order the handlers fire.

Here's part of the code:

```python

    #: Set the initial layout
    layout << AreaLayout(
        TabLayout(*editor_items(plugin.documents)),
        #etc...
        ],
    )

    Looper:
        iterable << plugin.documents
        DockItem:
            attr doc = loop_item

```

When the `Looper` updates first everything works. But when the `layout` updates first, it crashes with a NameError.  Is there any way to force one handler fire before the other? Why is it randomly using different orders?

**Comment by frmdstryr** [comment]
Come to think of it, this error seems a lot like the python 3.x `popup_view.enaml` error that causes travis to fail.

**Comment by MatthieuDartiailh** [comment]
Have you updated atom to latest master to fix the sortedmap issue ?

**Comment by frmdstryr** [comment]
Yes installed from git today.

**Comment by frmdstryr** [comment]
I added prints before and after the validator and

```python

    def apply_layout(self, layout):
        """ Apply a layout to the dock area.

        Parameters
        ----------
        layout : DockLayout
            The dock layout to apply to the managed area.

        """
        available = (i.objectName() for i in self._dock_items)
        print("## BEFORE ##", globals(), "## END BEFORE ##")
        DockLayoutValidator(available)(layout)
        print("## AFTER ##", globals(), "## END AFTER ##")
        LayoutBuilder(self)(layout)

```

And I'm getting


```
2017-11-30 01:00:41-0500 [-] ## BEFORE ## {'layout_hit_test': <function layout_hit_test at 0x7faa374a7598>, 'DockManager': <class 'enaml.qt.docking.dock_manager.DockManager'>, '__name__': 'enaml.qt.docking.dock_manager', 'LayoutSaver': <class 'enaml.qt.docking.layout_saver.LayoutSaver'>, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7faa374c0f98>, 'Atom': <class 'atom.atom.Atom'>, 'QRect': <class 'PyQt5.QtCore.QRect'>, '__spec__': ModuleSpec(name='enaml.qt.docking.dock_manager', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7faa374c0f98>, origin='/home/jrm/Workspace/app/venv/lib/python3.5/site-packages/enaml/qt/docking/dock_manager.py'), 'DockLayout': <class 'enaml.layout.dock_layout.DockLayout'>, 'QDockArea': <class 'enaml.qt.docking.q_dock_area.QDockArea'>, 'QObject': <class 'PyQt5.QtCore.QObject'>, 'QPoint': <class 'PyQt5.QtCore.QPoint'>, '__cached__': '/home/jrm/Workspace/app/venv/lib/python3.5/site-packages/enaml/qt/docking/__pycache__/dock_manager.cpython-35.pyc', 'QApplication': <class 'PyQt5.QtWidgets.QApplication'>, 'ProximityHandler': <class 'enaml.qt.docking.proximity_handler.ProximityHandler'>, '__file__': '/home/jrm/Workspace/app/venv/lib/python3.5/site-packages/enaml/qt/docking/dock_manager.py', 'Int': <class 'atom.scalars.Int'>, 'plug_frame': <function plug_frame at 0x7faa3747d598>, '__builtins__': {'NameError': <class 'NameError'>, 'id': <built-in function id>, 'frozenset': <class 'frozenset'>, 'FloatingPointError': <class 'FloatingPointError'>, 'BaseException': <class 'BaseException'>, '__name__': 'builtins', 'OSError': <class 'OSError'>, 'filter': <class 'filter'>, 'issubclass': <built-in function issubclass>, 'pow': <built-in function pow>, 'hasattr': <built-in function hasattr>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 'copyright': Copyright (c) 2001-2016 Python Software Foundation.
2017-11-30 01:00:41-0500 [-] All Rights Reserved.
2017-11-30 01:00:41-0500 [-] 
2017-11-30 01:00:41-0500 [-] Copyright (c) 2000 BeOpen.com.
2017-11-30 01:00:41-0500 [-] All Rights Reserved.
2017-11-30 01:00:41-0500 [-] 
2017-11-30 01:00:41-0500 [-] Copyright (c) 1995-2001 Corporation for National Research Initiatives.
2017-11-30 01:00:41-0500 [-] All Rights Reserved.
2017-11-30 01:00:41-0500 [-] 
2017-11-30 01:00:41-0500 [-] Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
2017-11-30 01:00:41-0500 [-] All Rights Reserved., 'input': <built-in function input>, 'map': <class 'map'>, 'False': False, '__import__': <built-in function __import__>, 'NotImplemented': NotImplemented, 'AttributeError': <class 'AttributeError'>, 'hex': <built-in function hex>, 'exec': <built-in function exec>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'format': <built-in function format>, 'next': <built-in function next>, 'IndentationError': <class 'IndentationError'>, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'divmod': <built-in function divmod>, 'callable': <built-in function callable>, 'display': <function display at 0x7faa367b1e18>, 'SyntaxError': <class 'SyntaxError'>, 'delattr': <built-in function delattr>, 'repr': <built-in function repr>, 'bytearray': <class 'bytearray'>, 'Exception': <class 'Exception'>, 'AssertionError': <class 'AssertionError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'setattr': <built-in function setattr>, 'license': Type license() to see the full license text, 'zip': <class 'zip'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'slice': <class 'slice'>, 'enumerate': <class 'enumerate'>, 'bytes': <class 'bytes'>, 'abs': <built-in function abs>, 'FutureWarning': <class 'FutureWarning'>, 'SystemExit': <class 'SystemExit'>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'ValueError': <class 'ValueError'>, 'True': True, 'ImportError': <class 'ImportError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'float': <class 'float'>, 'sum': <built-in function sum>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'UserWarning': <class 'UserWarning'>, 'isinstance': <built-in function isinstance>, 'EOFError': <class 'EOFError'>, 'getattr': <built-in function getattr>, 'chr': <built-in function chr>, 'reversed': <class 'reversed'>, 'ConnectionError': <class 'ConnectionError'>, 'bool': <class 'bool'>, 'staticmethod': <class 'staticmethod'>, 'classmethod': <class 'classmethod'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 'IndexError': <class 'IndexError'>, 'open': <built-in function open>, 'len': <built-in function len>, '__package__': '', 'ImportWarning': <class 'ImportWarning'>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'LookupError': <class 'LookupError'>, 'ord': <built-in function ord>, 'sorted': <built-in function sorted>, 'str': <class 'str'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
2017-11-30 01:00:41-0500 [-]     for supporting Python development.  See www.python.org for more information., 'InterruptedError': <class 'InterruptedError'>, 'Warning': <class 'Warning'>, 'all': <built-in function all>, 'eval': <built-in function eval>, 'locals': <built-in function locals>, 'NotImplementedError': <class 'NotImplementedError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'vars': <built-in function vars>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'complex': <class 'complex'>, 'EnvironmentError': <class 'OSError'>, 'print': <built-in function print>, 'BytesWarning': <class 'BytesWarning'>, 'ascii': <built-in function ascii>, 'int': <class 'int'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'MemoryError': <class 'MemoryError'>, 'round': <built-in function round>, 'ReferenceError': <class 'ReferenceError'>, 'any': <built-in function any>, 'StopIteration': <class 'StopIteration'>, 'RuntimeError': <class 'RuntimeError'>, 'property': <class 'property'>, 'SystemError': <class 'SystemError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'oct': <built-in function oct>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'GeneratorExit': <class 'GeneratorExit'>, 'compile': <built-in function compile>, 'OverflowError': <class 'OverflowError'>, 'TypeError': <class 'TypeError'>, 'range': <class 'range'>, 'RecursionError': <class 'RecursionError'>, 'min': <built-in function min>, '__debug__': True, 'BufferError': <class 'BufferError'>, 'globals': <built-in function globals>, 'tuple': <class 'tuple'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'IOError': <class 'OSError'>, 'Ellipsis': Ellipsis, 'iter': <built-in function iter>, 'TimeoutError': <class 'TimeoutError'>, 'ResourceWarning': <class 'ResourceWarning'>, 'None': None, 'FileExistsError': <class 'FileExistsError'>, 'object': <class 'object'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'type': <class 'type'>, 'bin': <built-in function bin>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'max': <built-in function max>, 'ArithmeticError': <class 'ArithmeticError'>, 'hash': <built-in function hash>, 'PermissionError': <class 'PermissionError'>, 'KeyError': <class 'KeyError'>, '__IPYTHON__': True, 'memoryview': <class 'memoryview'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'super': <class 'super'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'list': <class 'list'>, 'TabError': <class 'TabError'>, '__build_class__': <built-in function __build_class__>, 'UnicodeError': <class 'UnicodeError'>, 'set': <class 'set'>, 'help': Type help() for interactive help, or help(object) for help about object., 'dict': <class 'dict'>, 'dir': <built-in function dir>}, 'atomref': <class 'atom.catom.atomref'>, 'LayoutBuilder': <class 'enaml.qt.docking.layout_builder.LayoutBuilder'>, 'QDockWindow': <class 'enaml.qt.docking.q_dock_window.QDockWindow'>, '__doc__': None, 'List': <class 'atom.list.List'>, 'QDockContainer': <class 'enaml.qt.docking.q_dock_container.QDockContainer'>, 'QGuideRose': <class 'enaml.qt.docking.q_guide_rose.QGuideRose'>, 'Typed': <class 'atom.typed.Typed'>, 'DockOverlay': <class 'enaml.qt.docking.dock_overlay.DockOverlay'>, 'DockContainerMonitor': <class 'enaml.qt.docking.dock_manager.DockContainerMonitor'>, '__package__': 'enaml.qt.docking', 'iter_containers': <function iter_containers at 0x7faa374a7510>, 'Qt': <class 'PyQt5.QtCore.Qt'>, 'DockLayoutValidator': <class 'enaml.layout.dock_layout.DockLayoutValidator'>} ## END BEFORE ##
2017-11-30 01:00:41-0500 [-] /home/jrm/Workspace/app/venv/lib/python3.5/site-packages/enaml/qt/docking/dock_manager.py:185: enaml.layout.dock_layout.DockLayoutWarning: item 'editor-item-examples/pyboard/00.Basics/helloWorld.py' is not an available layout item
2017-11-30 01:00:41-0500 [-] ## AFTER ## {("item 'editor-item-examples/pyboard/00.Basics/helloWorld.py' is not an available layout item", <class 'enaml.layout.dock_layout.DockLayoutWarning'>, 185): True, 'version': 12} ## END AFTER ##

```

So the globals are completely gone after the validator fails (not sure how that's even possible).

How does enaml determine which subscription handlers get called first? Atom seems to always notify in the order the `observe` method is called. Does it depend on which node is compiled first?

**Comment by MatthieuDartiailh** [comment]
The error you give for the example comes from the fact that the namespace cannot access the fast locals from inside the list I will look into a fix. For your other error, I am a bit more perplex I must say, could also come up with a minimal reproducer that would help.

**Comment by tstordyallison** [comment]
IIRC, Atom observer callback order is essentially undefined. It feels like it’s the order you subscribe in, but that’s just an aretefact if the implementation. 

Once observers get added and removed (which happens whenever a traced expression runs) you’ll see it change.

**Comment by MatthieuDartiailh** [comment]
Looking more in details of your first example, I am starting to believe we are doing something wrong when compiling the event handler. Like all operators, it is compiled in 'eval' mode, which do not make any sense since it is not a simple Python expression. I wonder if we should not first change the compilation mode since in this case the function of the comprehension will use closures. @sccolbert why is this operator compiled using 'eval' rather than 'exec' ?

**Comment by frmdstryr** [comment]
@MatthieuDartiailh I can reproduce the crash by modifying the workbench example in https://github.com/nucleic/enaml/blob/master/examples/workbench/persistent_view.enaml as follows:

```python

enamldef ModelDockArea(PickableDockArea):
    attr items
    #: Crashes if set here
    layout = HSplitLayout(*[item['name'] for item in items])
    Looper:
        iterable << items
        Pane:
            name = loop_item['name']
            title = loop_item['title']


def create_new_area():
    """ Create a new pickable dock area with two child panes.

    """
    items = [
        dict(name='first', title='Pane 0'),
        dict(name='second', title='Pane 1')
    ]
    area = ModelDockArea(name='the_dock_area',items=items)
    #Pane(area, name='first', title='Pane 0')
    #Pane(area, name='second', title='Pane 1')
    # also crashes if setting the layout here
    # area.layout = HSplitLayout('first', 'second')
    return area

```

In python 2.7 it doesn't crash, but it doesn't display the items. In 3.5 it crashes with the strange NameError, so something is getting screwed up in after the DockLayoutValidator runs and fails. 

Also I'm not quite sure why it doesn't display in 2.7. My understanding is that `init_layout` should only fire after all child nodes are initialized but it doesn't seem to be finding them.

https://github.com/nucleic/enaml/blob/master/enaml/qt/qt_dock_area.py#L145-L155

It looks like everything should correctly. Any ideas?

**Comment by frmdstryr** [comment]
https://github.com/nucleic/enaml/blob/master/enaml/qt/qt_dock_area.py#L151

The `self.dock_items()` is returning an empty list because the `Looper` iterable is an empty list.
