### ISSUE TITLE
warning.warn in DockLayoutValidator causing exception on Python 3

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#246]
When the DockLayoutValidator detects an error it prints out a warning here:

https://github.com/nucleic/enaml/blob/master/enaml/layout/dock_layout.py#L389-L391

In python 3 this is causing the following NameError exception to be thrown:

```

(venv3) jrm@xps:~/Workspace/enaml$ python examples/workbench/sample.py 
Imported Persistent View!
Imported Persistent Workspace!
/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/docking/dock_manager.py:184: DockLayoutWarning: item 'first' is not an available layout item
  DockLayoutValidator(available)(layout)
Traceback (most recent call last):
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/q_deferred_caller.py", line 42, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/workbench/ui/workbench_menus.enaml", line 24, in invoke_action
    core.invoke_command(item.command, item.parameters, item)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/workbench/core/core_plugin.py", line 78, in invoke_command
    return command.handler(event)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/workbench/ui/ui_manifest.enaml", line 61, in select_workspace
    ui.select_workspace(event.parameters['workspace'])
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/workbench/ui/ui_plugin.py", line 158, in select_workspace
    self._model.workspace = new_workspace
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/standard_tracer.py", line 61, in __call__
    engine.update(owner, self.name)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 248, in update
    setattr(owner, name, pair.reader(owner, name))
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/include.py", line 85, in _observe_objects
    self.parent.insert_children(self, newvalue)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/object.py", line 228, in insert_children
    child_added(child)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 185, in child_added
    child.activate_proxy()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 214, in activate_proxy
    self.activate_bottom_up()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py", line 236, in activate_bottom_up
    self.proxy.activate_bottom_up()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/qt_toolkit_object.py", line 82, in activate_bottom_up
    self.init_layout()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/qt_dock_area.py", line 154, in init_layout
    self.apply_layout(d.layout)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/qt_dock_area.py", line 275, in apply_layout
    self.manager.apply_layout(layout)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/qt/docking/dock_manager.py", line 185, in apply_layout
    LayoutBuilder(self)(layout)
NameError: name 'LayoutBuilder' is not defined
```
Using print instead of the warning avoids the exception.

**Comment by MatthieuDartiailh** [comment]
This reminds me of the hold issue with system error we had because of Atom. I will try to look into it.

**Comment by sccolbert** [comment]
Can we please not use the word "crash" to mean "an exception was thrown"? If the process hasn't segfaulted or been otherwise forcibly terminated by the OS, then it hasn't crashed. Sorry, this is a pet-peeve of mine.

Otherwise, yeah, that exception shouldn't be possible. So something funky is happening. Do you have a stripped down example?

**Comment by frmdstryr** [comment]
Remove `'second'` in [examples/workbench/persistent_view.enaml](https://github.com/nucleic/enaml/blob/master/examples/workbench/persistent_view.enaml#L86) (or any other change to make the validator call warn) and run the workbench example (with python 3) to reproduce it.

**Comment by sccolbert** [comment]
And since `warnings` and `linecache` are both normal python code, you could literally step through it with pdb and see what's going on.

**Comment by frmdstryr** [comment]
Thanks!
