### ISSUE TITLE
Example observe_model_signal crashes/does not work

### ISSUE THREAD

**Issue by nasefbasdf** [nucleic/enaml#304]
Running the example from [https://enaml.readthedocs.io/en/latest/examples/ex_observe_model_signal.html](url) seems to work at first. However after the following sequence of interactions it always crashes/gets stuck:
1. click on ">" of the only item and select "add after"
2. click on ">" of the first/top item and select "delete"
3. click on ">" of the only item and select "add after", which will not work

I tested this on Windows 10 amd64, enaml 0.10.2, python 3.6 (PyQt5/PySide2), python 2.7 (PyQt4).

All 3 combinations print an exception (see below) and do nothing, except py36&PyQt5 which crashes.
```
(venv) C:\_1808>enaml-run observe_model_signal.enaml
Traceback (most recent call last):
  File "c:\l\venv\lib\site-packages\enaml\qt\qt_action.py", line 79, in on_triggered
    self.declaration.triggered(checked)
  File "c:\l\venv\lib\site-packages\enaml\core\declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "c:\l\venv\lib\site-packages\enaml\core\expression_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "c:\l\venv\lib\site-packages\enaml\core\standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "observe_model_signal.enaml", line 71, in f
    triggered :: model.add_value(index + 1, 'item %d' % len(model.values))
  File "observe_model_signal.enaml", line 39, in add_value
    self.values_changed('add')
  File "observe_model_signal.enaml", line 101, in on_changed
    self._values = model.values[:]
  File "c:\l\venv\lib\site-packages\enaml\core\standard_tracer.py", line 61, in __call__
    engine.update(owner, self.name)
  File "c:\l\venv\lib\site-packages\enaml\core\expression_engine.py", line 248, in update
    setattr(owner, name, pair.reader(owner, name))
  File "c:\l\venv\lib\site-packages\enaml\core\looper.py", line 76, in _observe_iterable
    self.refresh_items()
  File "c:\l\venv\lib\site-packages\enaml\core\looper.py", line 107, in refresh_items
    old_items.remove(iteration)
ValueError: list.remove(x): x not in list
```

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. I will look into it.

**Comment by frmdstryr** [comment]
Whether or not this is an issue is debatable, I think it's not. 

This is a side effect of how the Looper [refreshes items](https://github.com/nucleic/enaml/blob/master/enaml/core/looper.py#L87 ) and efficiently reuses widgets that have not changed.  The error only comes up when removing an object that is in the list multiple times.  

The design assumes that the Looper's items are unique (uses a sortedmap to store it's items) which, in my opinion, is good thing as it prevents programming errors. For example, if an object is accidentally added multiple times to a list, why would you want to display the same object twice? Typically you want a copy, not the same item. 

For this reason, it's often better to simply force the items to be unique or use an Atom object to hold the data for each list item when the same data is allowed.

**Comment by MatthieuDartiailh** [comment]
Thanks for the insight @frmdstryr. I missed that obviously when writing the example. The fix is then quite simple:
- update the example
- add a note in the example (and in the Looper example)
- add a note in the Looper documentation.
- potentially add a check in the Looper to exit early and with a nice error message
