### ISSUE TITLE
SyntaxError when using `.` in attr types

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#351]
Currently when attempting to set the type of an attr it cannot contain a `.` Ex:

```python
from enaml.widgets.api import *

import datetime
from datetime import date

enamldef Main(Window): window:
    attr date_t: date
    attr date_t2: datetime.date
```

It throws a syntax error

```python-traceback
Traceback (most recent call last):
  File "/Workspace/enaml/enaml/core/parser/base_parser.py", line 199, in parse
    return self.parser.parse(source, debug=0, lexer=lexer)
  File "/miniconda3/envs/enaml/lib/python3.7/site-packages/ply-3.11-py3.7.egg/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/miniconda3/envs/enaml/lib/python3.7/site-packages/ply-3.11-py3.7.egg/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/miniconda3/envs/enaml/lib/python3.7/site-packages/ply-3.11-py3.7.egg/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/Workspace/enaml/enaml/core/parser/base_parser.py", line 3405, in p_error
    syntax_error(msg, FakeToken(lexer, t.lineno))
  File "/Workspace/enaml/enaml/core/parser/base_lexer.py", line 71, in syntax_error
    _parsing_error(SyntaxError, message, token)
  File "/Workspace/enaml/enaml/core/parser/base_lexer.py", line 55, in _parsing_error
    raise ParsingError(klass, message, info)
enaml.core.parser.base_lexer.ParsingError: ('invalid syntax', ('example.enaml', 9, 0, '    attr date_t2: datetime.date'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/enaml/bin/enaml-run", line 11, in <module>
    load_entry_point('enaml', 'console_scripts', 'enaml-run')()
  File "/Workspace/enaml/enaml/runner.py", line 45, in main
    ast = parse(enaml_code, filename=enaml_file)
  File "/Workspace/enaml/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/Workspace/enaml/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "example.enaml", line 9
    attr date_t2: datetime.date
    ^
SyntaxError: invalid syntax

```

Is there a reason for this? If this is just not implemented I'd be willing to contribute a patch

**Comment by sccolbert** [comment]
There was a reason for it, I can't recall it at the moment though. I think
it was some very subtle edge case.

**Comment by frmdstryr** [comment]
Added in #359
