### ISSUE TITLE
image using base64 string

### ISSUE THREAD

**Issue by K3nn3th2** [nucleic/enaml#371]
when using a basestring to describe an images data attribute i get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_abstract_button.py", line 83, in on_clicked
    self.declaration.clicked(checked)
  File "/usr/lib/python2.7/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/usr/lib/python2.7/site-packages/enaml/core/expression_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "/usr/lib/python2.7/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "ReggaeLoaderPC.enaml", line 263, in f
    clicked :: target.objects = results[' '.join(scraperSelect.selected_item.split(' ')[:-1])]
  File "/usr/lib/python2.7/site-packages/enaml/core/include.py", line 85, in _observe_objects
    self.parent.insert_children(self, newvalue)
  File "/usr/lib/python2.7/site-packages/enaml/core/object.py", line 228, in insert_children
    child_added(child)
  File "/usr/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 185, in child_added
    child.activate_proxy()
  File "/usr/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  File "/usr/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 213, in activate_proxy
    child.activate_proxy()
  File "/usr/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 214, in activate_proxy
    self.activate_bottom_up()
  File "/usr/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 236, in activate_bottom_up
    self.proxy.activate_bottom_up()
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_toolkit_object.py", line 82, in activate_bottom_up
    self.init_layout()
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_container.py", line 334, in init_layout
    self._setup_manager()
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_container.py", line 538, in _setup_manager
    manager.set_items(self._create_layout_items())
  File "/usr/lib/python2.7/site-packages/enaml/layout/layout_manager.py", line 320, in set_items
    lc = child.layout_constraints()
  File "/usr/lib/python2.7/site-packages/enaml/layout/layout_manager.py", line 131, in layout_constraints
    return expand_constraints(self.constrainable(), self.constraints())
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_container.py", line 139, in constraints
    return self.declaration.layout_constraints()
  File "/usr/lib/python2.7/site-packages/enaml/widgets/image_view.py", line 69, in layout_constraints
    ratio = self.proxy.get_aspect_ratio()
  File "/usr/lib/python2.7/site-packages/enaml/qt/qt_image_view.py", line 272, in get_aspect_ratio
    return pm_size.width()/pm_size.height()
ZeroDivisionError: integer division or modulo by zero

i have tried setting raw_size but to no avail.
does anyone have any ideas how to fix the error?

**Comment by MatthieuDartiailh** [comment]
This is I believe fixed on latest master and I need to cut a release.

**Comment by K3nn3th2** [comment]
okay. thanks for the work!

**Comment by MatthieuDartiailh** [comment]
Thanks for posting a minimal reproduction example. I will try to have a look at it soon but do not hesitate to ping me.

**Comment by MatthieuDartiailh** [comment]
You need to decode the image to make it acceptable to qt as follows:

```python
from enaml.widgets.api import Window, Container, ImageView
from enaml.image import Image
import base64

enamldef Main(Window):

    Container:
        ImageView:
            image=Image(data=base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAAflBMVEX///8AAAD39/fKysqJiYkhISEGBgbj4+P6+vo8PDwaGhrh4eHQ0NAvLy8UFBRBQUF+fn5VVVUmJiZaWlpKSkq6urpfX1/y8vKPj48kJCQWFhZoaGiioqK5ubk3NzdFRUV0dHR4eHiampqmpqawsLAyMjLr6+vExMTY2NiMjIz58fMdAAAJOElEQVR4nMVb13rqMAxOQxYrhBnKKquQvv8LnvqXR0KGBz1fdBUgWLK2ZNnzXCAf3LLlajgN0yhKw+lwtcxug9xpKWvw15fZ6KMRRrPL2v+vyJNnNoyakQuIhtkz+U/oB/u0G7mAdD/4e+xxsKjv9lf8pxNThNpPiyD+U/ST+Yuw99vjuCRuf3zc7l9UYz75M/SDVWndcHNo3Vx82ISlV1d/I4nBl1ry6zDWvT4+lN9/n4THRq42NZVrHEzlnzaP9/BvheJHG6vNDDZCMdPtG+gH3wL9Xsv6VxjvBQnfznLIBPqzKR+f36P5Xfihx1mQkDmhj2fCnoxNOt+B6dIPxcJ6Zw5eYb2j/34ezf/zkH5oy53E8ZO+2K1t8XP2R5lVdBE68+urriQJP4tcxJBw41tYejN/r7xyeCASJtyHbyxilM9d39I+xOclP7S401dL+rgyZmY+JPZfrdED4uBTuiHawZX4MjTcz4P82Mg9mCQHERJGpMITilNTI3POCf/C2vV466v0AclVhMY9tj0mRZga8MAn/p/sffih4gN84cU/C/bxcSIpaPUgWVkqjAIu+UXAtxlzdUzhA7hir3S2sDF7rQmGQvVSQQJXvujAPvCtbboXIf9zcsptJyoZ2f3QCgUnKmAf/JPeI62JiY4xPL/OJAlc/b0zV0X2/CBN7PDKMfz/yF7/1QoqdyX197YlCsYwjV17ZMIGojeTybtIh8InfY6UFCZ4nrX9lRTA0f+V4Ca4cMHHJ9njjT1fu9RggB+XjljHP9lTPCdbHpPm0MUCFESQPcWF5hwJsXThWGLmbNdhVvCPQv2H0OdnJGWL9z6+m5bYvqUAd871lVjgh5hAHp1+XTB+kBo0ZKqPVGukXTCRBjjnXOABiGyKbOHMHqFpad3S4QI/3avrg0pFzrRKPC15lbN0AT5cds0hkgZa5H81eGxlQrYgJcspGCAAJXCDI0bMsVEP8e78DfwMCpGRRSTKhLJiLFtE0sbw7Vf1r2BA9H5JXYhKjsJpMlOyJzVgWVoc1Vmwku9ZwaNYr4uqPokclBIKnt3AQ4DJC/YEhVhV/gUGWMWgIhiGguHhMCjkDzmvRj6h/jFsIWTeJYadsdD8wB/LFo//7M2xDy61fsniInkacAqwIbL7jfw+ZKnG/kXjYuzDOAhOVq/YudzFnnhVRWlFIGXvgxvMB41BlVK5QBJpAPGmGT3W4GvGlHuQmOGVR4wYhKIde8IagVxzUdfKVgg6+3QRXzQpZT9j6XyTUDzB6hZiTXyaGqH3l13oGSy5GyQpYFdq4weJaVre877Kjw7gyXUn8IT+iQ+IP8mnRAAWMFWB1LnaJzAPEyc0aenRVoGXVD8fEseNPaXMFBGJzh7X+zRRtH41o6zu3wg/9/jctj/gIMBwqL/EC7dEKQyoOujx+wb8JyD7o9wD1o58ALKHb2Y2CXWgkAEzMXACWv1TQHkd5QgQyKd4OgiiwIshNsasJNTjD8zxC5WGta8kl88CG75i+hgxVqEY0XuhWNOnrwIFVgrBhdjvLuGkXCR1LEO5sAe9CnT4vyagHcHAIWjInuU7STAj9kAYF/GT1ggn7biaYSL/FUp0lYQLhshqFGZbIy0DWuJPO1AcQJbGjM3/tcS0qukccS4I6YSBLX7uZ5EGQQbFeV5U1wTrc1pamwpc7AmApiH1aGlX74lMuEltR7t+XqMFinW/LPhuUTBw50YWqkvHC3v83Al743tbrYH0PCP/pvODVk5IgC6+wjcsSb11BdGwG1UzDDWL+uylFdaONK96YQuO6Hy7ndtcpNa9R6CSRcrU5NWmPUK94hb+aLfF8pApNqej9dGCQaSgLfTp6gxCTWR0Q4sRnMXv5+bfi/YVAcR8Rv1J8+a6GcFN/H5r/l13SnKCnHonoHcR9K6EvZth746od1fcezD63+G4HXg47kxI4nNGmu6ckHQAT0i6UjLW4PmGflzsCbjoCOApWWNSyo+M4AF/2JNrUtoFPCltSstvEXUaQcAI1Dim5V0gENcLEzAFVQzqcVRNboVJF8jC5CKRePERmgudR8MAJkLa5FSadYEszVRxOkhp475smcBUUc47FaedIItTVZ4ztUx9r1xTQvTk0hzK806Q5blqUMApsiCvakoSPXVSrBsUnaAaFKpFA58Ei0RPB5xHo4cOvW1bNN1QatHIJhXJnvECTgppCvUYqK1r2aTqhlKTSrXppOwfsrFN33GZWrXpuqHcplONSkgcTkk1tv3yga9Fo1ID5UZlqVU7FRunkSTEqAGEwJsLxq1aHVRatapZvZUbp1PEQhL7MeULmzWrdVBtVqt2fZ6KjVNjm8yEWp4nkYIatOu18NKuVwcW2PiOWR0ddtLkAWVkqcjztQcWWng9sFBHNrTxTBJJR7n86EmR3H1ko4fXI5vSoRX8Azx5DlpGlHlzfCt1tN16aGUA9UOr0rEdNotQSB1/8oI5H85YVLfZcGxnAvVju9LBJR2swgBpoIFGfxJhf7O7Nb5XaDq4LB3dQh/IAEn9+UyRtL/F9c0B8qaj29LhNXn8b3hBYjxNIcgz0V97yN6ZlW0+vC4d31MxfmZfVufK/L3U+ZH7wHDL8X15gIGqbWTDMVWFO46vkCPe2qy/FdoGGEojHDz+oP8wJh5EAQ9cYs5aW1C3QesIR3mIhV6isRdhgCc5n5IxrmjLjhboGGIpj/Gs1diLNMBoKyfcntnR9RJD1xhPeZCJuj5p6ViNqeit+X8W0DnIVBnlonmHiFA+xZDo9E0vpBnlqgyz8cYTxZ9cGmCYvTHqph1mq4zzcZx7kvZRdWlmBoecjaAf56sONAYV9U+2O0mCy8Cn2UBjdaTzxicyudH6gbxl4zJvZDbSWR1q5YN4HzMu9/yHZyYO5mA61Fod6y245KNAMB2Xjab2IjAe630JQFL9xbT8L4V3By9kMdj8Otp9FNVQ6Kr8nuVo9+twey5rEefrU5bD7bXx/rtKgb8O9uK3H++vXXBQ0/JyUM4cXC44eLUrHmpa3mrky/mKh1e/5OJvhSDMJo4I3C+5NF3z4RcO9R1AucQ713y8potOyX2+M7529O5FJ6//q15e75fdvP6v+3m9X3gECf1e+WTQ86VXBj1f+wX0e/EZ0PPVb4JeL79L+MPr//8Ao6OGuLp5Hx4AAAAASUVORK5CYII='))
```

With this everything behaves as expected. I will clarify the documentation and sorry for the slow answer.
