### ISSUE TITLE
Add 'get' method to DynamicScope

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#376]
I'm not sure if something changed with pytest but if an error occurs in a declarative func it causes pytest (5.1.2) to bomb out: 

```python-traceback
tests/test_examples.py::test_example[gcode] 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/main.py", line 235, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/main.py", line 256, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/runner.py", line 72, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/runner.py", line 87, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/runner.py", line 169, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/skipping.py", line 123, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/runner.py", line 243, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/reports.py", line 277, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/python.py", line 818, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/nodes.py", line 253, in _repr_failure_py
INTERNALERROR>     self._prunetraceback(excinfo)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/python.py", line 805, in _prunetraceback
INTERNALERROR>     excinfo.traceback = ntraceback.filter()
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/_code/code.py", line 338, in filter
INTERNALERROR>     return Traceback(filter(fn, self), self._excinfo)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/_code/code.py", line 294, in __init__
INTERNALERROR>     list.__init__(self, tb)
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/_code/code.py", line 328, in <lambda>
INTERNALERROR>     def filter(self, fn=lambda x: not x.ishidden()):
INTERNALERROR>   File "/home/user/miniconda3/envs/test/lib/python3.6/site-packages/_pytest/_code/code.py", line 248, in ishidden
INTERNALERROR>     tbh = f.f_locals.get(
INTERNALERROR> AttributeError: 'enaml.dynamicscope.DynamicScope' object has no attribute 'get'

```
If I pull the declarative func out to a regular def, pytest correctly reports the error and keeps going.  Is it possible to add a get method to dynamicscope?  I'll see if I can make an example to demonstrate this.

**Comment by MatthieuDartiailh** [comment]
According to the documentation locals is expected to be dict, and we are pretending that `DynamicScope` is a subclass of `dict` so it is not so surprising that we would be bitten by something like this. Implementing get should be fairly straightforward, would you need a quick release ?

**Comment by frmdstryr** [comment]
No quick release needed.  

Also I remember seeing a somewhat related issue that'd be nice to have while this is being fixed...  If IPython is embedded within a declarative func (for debugging) it dosen't work because it attempts to copy the namespace using `items` in  [IPython/terminal/embed.py#L311](https://github.com/ipython/ipython/blob/0acd580fce7192044a6f846dd09d31d498018347/IPython/terminal/embed.py#L311) which also isn't implemented on DynamicScope.

**Comment by MatthieuDartiailh** [comment]
`items` is much more tricky ! 

In a normal dictionary, items is expected to be always in sync with the dictionary. Also items is list like and implementing the dynamic nature of the DynamicScope in items won't be really possible and would require to pull all possible attributes and somewhat defeat the dynamic nature of it.

**Comment by frmdstryr** [comment]
Added in  #394
