### ISSUE TITLE
Backstring in f-string syntax error reporting wrong line

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#377]
I should know better but the error message for using a backslash in an f-string in enaml is reporting the error at a line that doesn't make sense.

```python
from enaml.widgets.api import Window, Container, Label, PushButton

enamldef Main(Window): window:
    Container:
        attr path = r'C:\\fakepath\\SomeData.csv'
        PushButton:
            text = 'Set path'
            clicked ::
                # Backslash in f-string not allowed
                label.text = f'Import {path.split("\\")[-1]}'
        PushButton:
            text = 'Clear path'
            clicked :: label.text = ''
        Label: label:
            text = ''
```

It's reporting at line 13 but I'd expect it to be at the f-string line (10).  

```

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/enaml3/bin/enaml-run", line 11, in <module>
    load_entry_point('enaml', 'console_scripts', 'enaml-run')()
  File "/home/user/Workspace/enaml/enaml/runner.py", line 45, in main
    ast = parse(enaml_code, filename=enaml_file)
  File "/home/user/Workspace/enaml/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/home/user/Workspace/enaml/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "tests/example.enaml", line 13
    clicked :: label.text = ''
    ^
SyntaxError: invalid syntax

```

It would be nice if the original error could be retained as well (if possible).
```python

path = r'C:\fakepath\SomeData.csv'
path
Out[2]: 'C:\\fakepath\\SomeData.csv'

x = f'Importing {path.split("\\")[-1]}...'
  File "<ipython-input-3-6ed1e7ff0f7d>", line 1
    x = f'Importing {path.split("\\")[-1]}...'
       ^
SyntaxError: f-string expression part cannot include a backslash
```

**Comment by MatthieuDartiailh** [comment]
Thanks for the report.

**Comment by MatthieuDartiailh** [comment]
#378 Should fix your issue. I need to add tests though.
