### ISSUE TITLE
DockArea does not appear to like floating point values anymore

### ISSUE THREAD

**Issue by buranconsult** [nucleic/enaml#472]
I get this error message when attempting to drag a DockItem:

```
Traceback (most recent call last):
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\q_dock_frame.py", line 226, in mouseMoveEvent
    if self.titleBarMouseMoveEvent(event):
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\q_dock_container.py", line 736, in titleBarMouseMoveEvent
    self.manager().drag_move_frame(self, target_pos, global_pos)
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\dock_manager.py", line 464, in drag_move_frame
    self._update_drag_overlay(frame, mouse_pos)
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\dock_manager.py", line 627, in _update_drag_overlay
    overlay.mouse_over_area(target, widget, local)
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\dock_overlay.py", line 521, in mouse_over_area
    band_geo = self._band_geometry(widget, guide)
  File "c:\users\bburan\projects\consulting\ncrar\biosemi\src\enaml\enaml\qt\docking\dock_overlay.py", line 323, in _band_geometry
    rect.setHeight(rect.height() / 3)
TypeError: setHeight(self, int): argument 1 has unexpected type 'float'
```
This is on Windows 10. Installed Qt versions are:
```
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
QtPy==2.0.0
```

**Comment by sccolbert** [comment]
That looks like a Python 2 relic, where that would have been integer
division.

But I guess PyQt had been coercing that for us up until now.
