### ISSUE TITLE
0.18.0 seems to have broken inkcut

### ISSUE THREAD

**Issue by raboof** [nucleic/enaml#557]
When updating enaml in inkcut to 0.18.0, I get the following:

```
  File "/nix/store/qyjrpynnjpr73hcqmyvr0gkwxrni7y8j-inkcut-2.1.5/lib/python3.12/site-packages/inkcut/app.py", line 99, in main
    workbench.run()
  File "/nix/store/qyjrpynnjpr73hcqmyvr0gkwxrni7y8j-inkcut-2.1.5/lib/python3.12/site-packages/inkcut/core/workbench.py", line 161, in run
    ui = self.get_plugin('enaml.workbench.ui')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/workbench.py", line 144, in get_plugin
    plugin = manifest.factory()
             ^^^^^^^^^^^^^^^^^^
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/ui_manifest.enaml", line 18, in ui_plugin_factory
    from .ui_plugin import UIPlugin
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/ui_plugin.py", line 26, in <module>
    from .workbench_window import WorkbenchWindow
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/core/import_hooks.py", line 147, in exec_module
    exec(code, module.__dict__)
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 16, in 
    def make_title(primary, workspace):
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 1, in WorkbenchWindow
    #------------------------------------------------------------------------------
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 35, in WorkbenchWindow
    objects << [w for w in [window_model.workspace.content] if w]
ValueError: invalid end_lineno, expected >= 1, got 0

Traceback (most recent call last):
  File "/nix/store/qyjrpynnjpr73hcqmyvr0gkwxrni7y8j-inkcut-2.1.5/bin/.inkcut-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/qyjrpynnjpr73hcqmyvr0gkwxrni7y8j-inkcut-2.1.5/lib/python3.12/site-packages/inkcut/app.py", line 99, in main
    workbench.run()
  File "/nix/store/qyjrpynnjpr73hcqmyvr0gkwxrni7y8j-inkcut-2.1.5/lib/python3.12/site-packages/inkcut/core/workbench.py", line 161, in run
    ui = self.get_plugin('enaml.workbench.ui')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/workbench.py", line 144, in get_plugin
    plugin = manifest.factory()
             ^^^^^^^^^^^^^^^^^^
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/ui_manifest.enaml", line 18, in ui_plugin_factory
    from .ui_plugin import UIPlugin
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/ui_plugin.py", line 26, in <module>
    from .workbench_window import WorkbenchWindow
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/core/import_hooks.py", line 147, in exec_module
    exec(code, module.__dict__)
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 16, in 
    def make_title(primary, workspace):
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 1, in WorkbenchWindow
    #------------------------------------------------------------------------------
  File "/nix/store/f7246ka4bp99vsdplg7l4yxsdys3r3rx-python3.12-enaml-0.18.0/lib/python3.12/site-packages/enaml/workbench/ui/workbench_window.enaml", line 35, in WorkbenchWindow
    objects << [w for w in [window_model.workspace.content] if w]
ValueError: invalid end_lineno, expected >= 1, got 0
```

I can't easily relate that to any of the changes in 0.18.0, but it worked with 0.17.0. Does this ring any bell?

(reported in inkcut as https://github.com/inkcut/inkcut/issues/386)

**Comment by MatthieuDartiailh** [comment]
Can you try updating bytecode ? I have forgotten to increase the bound on it.

**Comment by raboof** [comment]
thanks for the pointer, after updating bytecode from 0.15.1 to 0.16.0 it starts fine again!
